server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: ssh_honeypot
    static_configs:
      - targets:
          - localhost
        labels:
          job: ssh_honeypot
          logtype: honeypot
          __path__: /app/logs/honeypot.log

      - targets:
          - localhost
        labels:
          job: ssh_honeypot
          logtype: exception
          __path__: /app/logs/exception.log
