{
 "title": "SSH Honeypot",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Top Countries",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(country) (count_over_time({logtype=\"honeypot\"} |= `[AUTH]` |= `Country:` | regexp `Country: (?P<country>[^|]+)` [$__range]))"
    }
   ]
  },
  {
   "title": "Top used commands",
   "type": "table",
   "description": "The top commands that ran",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(cmd) (count_over_time({logtype=\"honeypot\"} |= `Command:` | regexp `Command: (?P<cmd>\\w+)` [$__range]))"
    }
   ]
  },
  {
   "title": "Top username/password combinations",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(username, password) (count_over_time({logtype=\"honeypot\"} |= `[AUTH]` | regexp `Username: (?P<username>\\S+) \\| Password: (?P<password>\\S+)` [$__range])))"
    }
   ]
  },
  {
   "title": "Top IP-Addresses",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(ip) (count_over_time({logtype=\"honeypot\"} |= `[AUTH]` |= `Username` | regexp `IP: (?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+\\|\\s+Country:.*?\\|\\s+Username: (?P<username>\\S+)\\s+\\|\\s+Password: (?P<password>\\S+)` [$__range]))"
    }
   ]
  },
  {
   "title": "Raw Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{logtype=\"honeypot\"} |= ``"
    }
   ]
  },
  {
   "title": "Raw Exception log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{logtype=\"exception\"} |= ``"
    }
   ]
  },
  {
   "title": "Signin Attempts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({logtype=\"honeypot\"} |= `[AUTH]` |= `Session opened!` [$__range])",
     "legendFormat": "Successful Signins"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({logtype=\"honeypot\"} |= `[AUTH]` != `Session opened!` [$__range])",
     "legendFormat": "Signins"
    }
   ]
  },
  {
   "title": "Incoming Connections (over time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"ssh_honeypot\", logtype=\"honeypot\"} |= \"Connection from\" [$__range])"
    }
   ]
  },
  {
   "title": "Used Commands",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(cmd) (count_over_time({logtype=\"honeypot\"} |= `Command:` | regexp `Command: (?P<cmd>\\w+)` [$__range])))"
    }
   ]
  }
 ]
}